language: ruby

rvm: 2.2.4

env:
  global:
    - USE_TESTING_TIMEOUTS: "true"
    - OPENSTUDIO_VERSION=2.7.1 OPENSTUDIO_VERSION_SHA=b8d47b8b9d

before_install:
  - ./ci/travis/setup.sh
script:
  - ./ci/travis/test.sh
after_failure:
  - ./ci/travis/print_logs.sh

services:
  - docker

jobs:
  include:
    - stage: test
      os: linux
      sudo: required
      dist: trusty
      env: BUILD_TYPE=test
    - stage: test
      os: osx
      osx_image: xcode8 # OSX 10.11
      env: BUILD_TYPE=test
    - stage: test
      os: osx
      osx_image: xcode9.2 # OSX 10.12
      env: BUILD_TYPE=test
    - stage: test
      os: osx
      osx_image: xcode9.4 # OSX 10.13
      env: BUILD_TYPE=test
    - stage: test
      os: linux
      sudo: required
      dist: trusty
      env: BUILD_TYPE=docker
      before_install: skip
      before_script:
        - docker pull nrel/openstudio:$OPENSTUDIO_VERSION
        - docker pull nrel/openstudio-cli:$OPENSTUDIO_VERSION
      script:
        - docker run -v $(pwd):/var/simdata/openstudio nrel/openstudio:$OPENSTUDIO_VERSION openstudio run -w basic_osw/in.osw
        - cat basic_osw/run/measure_attributes.json
        - docker run -v $(pwd):/var/simdata/openstudio nrel/openstudio-cli:$OPENSTUDIO_VERSION openstudio run -w basic_osw/in.osw
        - cat basic_osw/run/measure_attributes.json
        # Wait until 2.6.0 or 2.6.1 is updated with the most recent standards to reenable gbxml test
        # - docker run -v $(pwd):/var/simdata/openstudio nrel/openstudio:$OPENSTUDIO_VERSION openstudio run -w gbxml_osw/in.osw
        # The command above does not return a non-zero exist status, so look for the measure_attributes.json file
        # - cat gbxml_osw/run/measure_attributes.json
